apiVersion: v1
kind: PersistentVolume
metadata:
  name: spooler-pv 
  labels:
    type: amazonEBS
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  awsElasticBlockStore:
    volumeID: vol-XXX 
    fsType: ext4
