apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: sqs-spooler 
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        volumeMounts:
        - mountPath: "/spooler"
          name: pvd
        ports:
        - containerPort: 80
      volumes:
      - name: pvd
        persistentVolumeClaim:
          claimName: spooler-pvc
